### ISSUE TITLE
url生成算法问题

### ISSUE THREAD

**Issue by dolo** [hkslover/ximalaya#5]
python main.py
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\dolo\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\dolo\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 74, in download
    file1 = requests.get(url,headers = headers)
  File "C:\Users\dolo\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\dolo\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\dolo\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "C:\Users\dolo\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "C:\Users\dolo\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "C:\Users\dolo\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

**Comment by dolo** [comment]
好像是获取url的地方有问题，只能获得title，拿不到playUrl64

**Comment by dolo** [comment]
{
	'trackId': 192421850,
	'trackRecordId': 217554848,
	'uid': 9216785,
	'playUrl64': '',
	'playUrl32': '',
	'playPathHq': '',
	'playPathAacv164': '',
	'playPathAacv224': '',
	'title': '【海底报告歌曲】第100集：翻车鱼',
	'duration': 60,
	'albumId': 20974886,
	'albumTitle': '海底小纵队广播剧【官方正版】',
	'albumImage': 'http://imagev2.xmcdn.com/group57/M03/21/5A/wKgLd1yPfJ
	bTGCZzAAPVWxI7JV8381.jpg!op_type = 5 & upload_type = album & device_type = ios & name = medium & magick = png ', '
	isPaid ': True, '
	isFree ': False, '
	isVideo ': False, '
	isDraft ': False, '
	isRichAudio ': False, '
	isAuthorized ': False, '
	priceTypeId ': 2, '
	sampleDuration ': 60, '
	priceTypeEnum ': 2, '
	type ': 0, '
	relatedId ': 0, '
	orderNo ': 224, '
	vipFirstStatus ': 0}

**Comment by hkslover** [comment]
我用的播放接口不是trackid的，而且不支持付费，vip版的请看github的pay目录

**Comment by dolo** [comment]
> 我用的播放接口不是trackid的，而且不支持付费，vip版的请看github的pay目录

嗯发现了……多谢回复，确实免费版的有url，收费版的没有
