### ISSUE TITLE
我在mac下想打包为app时，出现如下错误：

### ISSUE THREAD

**Issue by justincnn** [hkslover/ximalaya#6]
Failed to execute script pyi_rth__tkinter

请问这个有办法解决么？

**Comment by wqwangwei** [comment]
mac不打包能否使用？方法是什么？我在mac执行报错了
python3 PayDownload.py
Please enter your album ID:9724463
Traceback (most recent call last):
  File "PayDownload.py", line 71, in <module>
    getData(albumid)
  File "PayDownload.py", line 44, in getData
    getPlayerUrl(title,trackId)
  File "PayDownload.py", line 54, in getPlayerUrl
    response = requests.get(url,headers = headers)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1293, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1230, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'1&_token=\n'

**Comment by hkslover** [comment]
填写vip账号的 token

**Comment by wqwangwei** [comment]
> 填写vip账号的 token

我填写了VIP账号token，可是还是有报错

**Comment by wqwangwei** [comment]
我在喜马拉雅兑换了一个7天vip，用URL测试
"isAuthorized":true VIP的token应该是生效了

**Comment by hkslover** [comment]
安装nodejs
