### ISSUE TITLE
安装了nodejs，运行报错，请看下

### ISSUE THREAD

**Issue by MondayPink** [hkslover/ximalaya#9]
C:\ximalaya-master\ximalaya-master\pay>C:\Python38\python PayDownload.py
Please enter your album ID:4626667
Traceback (most recent call last):
  File "PayDownload.py", line 69, in <module>
    getData(albumid)
  File "PayDownload.py", line 42, in getData
    getPlayerUrl(title,trackId)
  File "PayDownload.py", line 56, in getPlayerUrl
    result = execjs.compile(js_code).call('get_player_url',data)
  File "C:\Python38\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "C:\Python38\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "C:\Python38\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "C:\Python38\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "C:\Python38\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "C:\Python38\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: TypeError: 'undefined' 为 null 或不是对象

**Comment by MondayPink** [comment]
补充：
txt已经添加了
1&_token=XXX
还是这样

**Comment by mgsky1** [comment]
不能用Windows运行，我在Windows下运行也是这样，后来换成macOS就可以用了，不知道Linux下可不可以，我感觉也是可以的

**Comment by prehistoric-penguin** [comment]
Ubuntu 可以运行，点赞
